Support for more scendarios in run_multi_rejoin
Add support for more test scenarios in the `run_multi_rejoin` script.

diff --git a/scripts/run_multi_rejoin b/scripts/run_multi_rejoin
--- a/scripts/run_multi_rejoin
+++ b/scripts/run_multi_rejoin
@@ -11,21 +11,41 @@ Runs a multi-peer mesh re-join test.
 
 OPTIONS:
    -h   Show this message.
+   -m   Use meshkit (otherwise uses iw)
+   -l   Use "mesh leave" for iw, for meshkit this does nothing
+   -c   Close the door
+   -d   Try to 'fix' the rejoin problem by recreating the interface
+   -b   Leave ping running in the background
+   -t   Always use a "2nd" interface
 EOF
 }
 
+SECONDIFACE=
+MESHKIT=
+LEAVE=
+CLOSETHEDOOR=
+DELIFACE=
+PINGBG=
+
 # parse the incoming parameters
-while getopts "h" options; do
+while getopts "hmlcdt" options; do
     case $options in
         h ) usage; exit 0;;
+        m ) MESHKIT=1 ;;
+        l ) LEAVE=1;;
+        c ) CLOSETHEDOOR=1;;
+        d ) DELIFACE=1;;
+        p ) PINGBG=1;;
+        t ) SECONDIFACE=1;;
         * ) usage; exit 1;;
     esac
 done
 
-CHANNEL=5
+CHANNEL=7
 HT="NO_HT"
 
 reboot_phones
+sleep_countdown 10
 
 serials=$(adbs shell getprop ro.serialno)
 
@@ -33,40 +53,102 @@ serial1=$(echo $serials | cut -d' ' -f1)
 serial2=$(echo $serials | cut -d' ' -f2)
 serial3=$(echo $serials | cut -d' ' -f3)
 
-ip1=$(join_mesh_meshkit $CHANNEL $HT $serial1)
-ip2=$(join_mesh_meshkit $CHANNEL $HT $serial2)
-ip3=$(join_mesh_meshkit $CHANNEL $HT $serial3)
-sleep 2
+if [[ -n $MESHKIT ]]; then
+    meshup=join_mesh_meshkit
+else
+    meshup=join_mesh
+fi
 
-#ip1=$(gen_ip $serial1)
-#ip2=$(gen_ip $serial2)
-#ip3=$(gen_ip $serial3)
+if [[ -n $SECONDIFACE ]]; then
+    $meshup $CHANNEL $HT $serial1 &>/dev/null
+    $meshup $CHANNEL $HT $serial2 &>/dev/null
+    $meshup $CHANNEL $HT $serial3 &>/dev/null
+    adbs shell iw dev mesh0 del
+    sleep_countdown 2
+fi
 
-echo_eval adb -s $serial1 shell ping -c3 $ip2 &
-echo_eval adb -s $serial1 shell ping -c3 $ip3 &
+ip1=$($meshup $CHANNEL $HT $serial1)
+ip2=$($meshup $CHANNEL $HT $serial2)
+ip3=$($meshup $CHANNEL $HT $serial3)
 
-echo_eval adb -s $serial2 shell ping -c3 $ip1 &
-echo_eval adb -s $serial2 shell ping -c3 $ip3 &
+echo "Waiting for mesh to settle..."
+sleep_countdown 5
 
-echo_eval adb -s $serial3 shell ping -c3 $ip1 &
-echo_eval adb -s $serial3 shell ping -c3 $ip2 &
+if [[ -z $PINGBG ]]; then
+    PING_OPT="-f -c5"
+else
+    PING_OPT="-i.2"
+fi
 
-wait
+echo_eval adb -s $serial1 shell sh -c "ping $PING_OPT $ip2 &>/dev/null" &
+echo_eval adb -s $serial1 shell sh -c "ping $PING_OPT $ip3 &>/dev/null" &
+
+echo_eval adb -s $serial2 shell sh -c "ping $PING_OPT $ip1 &>/dev/null" &
+echo_eval adb -s $serial2 shell sh -c "ping $PING_OPT $ip3 &>/dev/null" &
+
+echo_eval adb -s $serial3 shell sh -c "ping $PING_OPT $ip1 &>/dev/null" &
+echo_eval adb -s $serial3 shell sh -c "ping $PING_OPT $ip2 &>/dev/null" &
+
+if [[ -z $PINGBG ]]; then
+    wait
+fi
 
 adbs shell iw dev mesh0 mpath dump
 
-reboot_one_phone $serial1
+if [[ -n $MESHKIT ]]; then
+    echo_eval adb -s $serial1 shell mesh mesh0 down
+else
+    if [[ -n $LEAVE ]]; then
 
-join_mesh_meshkit $CHANNEL $HT $serial1 || die "joining mesh failed"
-sleep 2
+        # TODO: This will cause the test to fail!
+        echo_eval adb -s $serial1 shell iw dev mesh0 mesh leave
 
-echo_eval adb -s $serial1 shell ping -c3 $ip2 
-echo_eval adb -s $serial1 shell ping -c3 $ip3 
+    elif [[ -n $CLOSETHEDOOR ]]; then
+        echo
+        echo "!!!!!!!!!!!!!!!!!!!!"
+        echo "!! CLOSE THE DOOR !!"
+        echo "!!!!!!!!!!!!!!!!!!!!"
+        echo
 
-echo_eval adb -s $serial2 shell ping -c3 $ip1 
-echo_eval adb -s $serial2 shell ping -c3 $ip3 
+        read
 
-echo_eval adb -s $serial3 shell ping -c3 $ip1 
-echo_eval adb -s $serial3 shell ping -c3 $ip2 
+        sleep_countdown 5
 
-wait
+        echo
+        echo "!!!!!!!!!!!!!!!!!!!!"
+        echo "!! OPEN THE DOOR  !!"
+        echo "!!!!!!!!!!!!!!!!!!!!"
+        echo
+
+        read
+
+        if [[ -z $DELIFACE ]]; then
+            # Set this so it doesn't try to recreate the interface
+            LEAVE=1
+        else
+            echo_eval adb -s $serial1 shell iw dev mesh0 del
+        fi
+
+    else
+        echo_eval adb -s $serial1 shell iw dev mesh0 del
+    fi
+fi
+sleep_countdown 5
+
+$meshup $CHANNEL $HT $serial1 $LEAVE || die "joining mesh failed"
+sleep_countdown 5
+
+echo_eval adb -s $serial1 shell ping -c20 -f $ip2 
+echo_eval adb -s $serial1 shell ping -c20 -f $ip3 
+
+echo_eval adb -s $serial2 shell ping -c20 -f $ip1 
+echo_eval adb -s $serial2 shell ping -c20 -f $ip3 
+
+echo_eval adb -s $serial3 shell ping -c20 -f $ip1 
+echo_eval adb -s $serial3 shell ping -c20 -f $ip2 
+
+if [[ -n $PINGBG ]]; then
+    echo_eval adbs shell killall ping
+else
+    wait
+fi
